QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    board.cpp \
    cardpic.cpp \
    cardset.cpp \
    game.cpp \
    main.cpp \
    player.cpp

HEADERS += \
    board.h \
    cardpic.h \
    cardset.h \
    game.h \
    player.h

FORMS += \
    game.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    PNGs/cards/Set_A/large/card_a_c10_large.png \
    PNGs/cards/Set_A/large/card_a_c2_large.png \
    PNGs/cards/Set_A/large/card_a_c3_large.png \
    PNGs/cards/Set_A/large/card_a_c4_large.png \
    PNGs/cards/Set_A/large/card_a_c5_large.png \
    PNGs/cards/Set_A/large/card_a_c6_large.png \
    PNGs/cards/Set_A/large/card_a_c7_large.png \
    PNGs/cards/Set_A/large/card_a_c8_large.png \
    PNGs/cards/Set_A/large/card_a_c9_large.png \
    PNGs/cards/Set_A/large/card_a_ca_large.png \
    PNGs/cards/Set_A/large/card_a_cj_large.png \
    PNGs/cards/Set_A/large/card_a_ck_large.png \
    PNGs/cards/Set_A/large/card_a_cq_large.png \
    PNGs/cards/Set_A/large/card_a_d10_large.png \
    PNGs/cards/Set_A/large/card_a_d2_large.png \
    PNGs/cards/Set_A/large/card_a_d3_large.png \
    PNGs/cards/Set_A/large/card_a_d4_large.png \
    PNGs/cards/Set_A/large/card_a_d5_large.png \
    PNGs/cards/Set_A/large/card_a_d6_large.png \
    PNGs/cards/Set_A/large/card_a_d7_large.png \
    PNGs/cards/Set_A/large/card_a_d8_large.png \
    PNGs/cards/Set_A/large/card_a_d9_large.png \
    PNGs/cards/Set_A/large/card_a_da_large.png \
    PNGs/cards/Set_A/large/card_a_dj_large.png \
    PNGs/cards/Set_A/large/card_a_dk_large.png \
    PNGs/cards/Set_A/large/card_a_dq_large.png \
    PNGs/cards/Set_A/large/card_a_h10_large.png \
    PNGs/cards/Set_A/large/card_a_h2_large.png \
    PNGs/cards/Set_A/large/card_a_h3_large.png \
    PNGs/cards/Set_A/large/card_a_h4_large.png \
    PNGs/cards/Set_A/large/card_a_h5_large.png \
    PNGs/cards/Set_A/large/card_a_h6_large.png \
    PNGs/cards/Set_A/large/card_a_h7_large.png \
    PNGs/cards/Set_A/large/card_a_h8_large.png \
    PNGs/cards/Set_A/large/card_a_h9_large.png \
    PNGs/cards/Set_A/large/card_a_ha_large.png \
    PNGs/cards/Set_A/large/card_a_hj_large.png \
    PNGs/cards/Set_A/large/card_a_hk_large.png \
    PNGs/cards/Set_A/large/card_a_hq_large.png \
    PNGs/cards/Set_A/large/card_a_s10_large.png \
    PNGs/cards/Set_A/large/card_a_s2_large.png \
    PNGs/cards/Set_A/large/card_a_s3_large.png \
    PNGs/cards/Set_A/large/card_a_s4_large.png \
    PNGs/cards/Set_A/large/card_a_s5_large.png \
    PNGs/cards/Set_A/large/card_a_s6_large.png \
    PNGs/cards/Set_A/large/card_a_s7_large.png \
    PNGs/cards/Set_A/large/card_a_s8_large.png \
    PNGs/cards/Set_A/large/card_a_s9_large.png \
    PNGs/cards/Set_A/large/card_a_sa_large.png \
    PNGs/cards/Set_A/large/card_a_sj_large.png \
    PNGs/cards/Set_A/large/card_a_sk_large.png \
    PNGs/cards/Set_A/large/card_a_sq_large.png \
    PNGs/cards/Set_A/small/card_a_c10.png \
    PNGs/cards/Set_A/small/card_a_c2.png \
    PNGs/cards/Set_A/small/card_a_c3.png \
    PNGs/cards/Set_A/small/card_a_c4.png \
    PNGs/cards/Set_A/small/card_a_c5.png \
    PNGs/cards/Set_A/small/card_a_c6.png \
    PNGs/cards/Set_A/small/card_a_c7.png \
    PNGs/cards/Set_A/small/card_a_c8.png \
    PNGs/cards/Set_A/small/card_a_c9.png \
    PNGs/cards/Set_A/small/card_a_ca.png \
    PNGs/cards/Set_A/small/card_a_cj.png \
    PNGs/cards/Set_A/small/card_a_ck.png \
    PNGs/cards/Set_A/small/card_a_cq.png \
    PNGs/cards/Set_A/small/card_a_d10.png \
    PNGs/cards/Set_A/small/card_a_d2.png \
    PNGs/cards/Set_A/small/card_a_d3.png \
    PNGs/cards/Set_A/small/card_a_d4.png \
    PNGs/cards/Set_A/small/card_a_d5.png \
    PNGs/cards/Set_A/small/card_a_d6.png \
    PNGs/cards/Set_A/small/card_a_d7.png \
    PNGs/cards/Set_A/small/card_a_d8.png \
    PNGs/cards/Set_A/small/card_a_d9.png \
    PNGs/cards/Set_A/small/card_a_da.png \
    PNGs/cards/Set_A/small/card_a_dj.png \
    PNGs/cards/Set_A/small/card_a_dk.png \
    PNGs/cards/Set_A/small/card_a_dq.png \
    PNGs/cards/Set_A/small/card_a_h10.png \
    PNGs/cards/Set_A/small/card_a_h2.png \
    PNGs/cards/Set_A/small/card_a_h3.png \
    PNGs/cards/Set_A/small/card_a_h4.png \
    PNGs/cards/Set_A/small/card_a_h5.png \
    PNGs/cards/Set_A/small/card_a_h6.png \
    PNGs/cards/Set_A/small/card_a_h7.png \
    PNGs/cards/Set_A/small/card_a_h8.png \
    PNGs/cards/Set_A/small/card_a_h9.png \
    PNGs/cards/Set_A/small/card_a_ha.png \
    PNGs/cards/Set_A/small/card_a_hj.png \
    PNGs/cards/Set_A/small/card_a_hk.png \
    PNGs/cards/Set_A/small/card_a_hq.png \
    PNGs/cards/Set_A/small/card_a_s10.png \
    PNGs/cards/Set_A/small/card_a_s2.png \
    PNGs/cards/Set_A/small/card_a_s3.png \
    PNGs/cards/Set_A/small/card_a_s4.png \
    PNGs/cards/Set_A/small/card_a_s5.png \
    PNGs/cards/Set_A/small/card_a_s6.png \
    PNGs/cards/Set_A/small/card_a_s7.png \
    PNGs/cards/Set_A/small/card_a_s8.png \
    PNGs/cards/Set_A/small/card_a_s9.png \
    PNGs/cards/Set_A/small/card_a_sa.png \
    PNGs/cards/Set_A/small/card_a_sj.png \
    PNGs/cards/Set_A/small/card_a_sk.png \
    PNGs/cards/Set_A/small/card_a_sq.png \
    PNGs/cards/Set_B/large/card_b_c10_large.png \
    PNGs/cards/Set_B/large/card_b_c2_large.png \
    PNGs/cards/Set_B/large/card_b_c3_large.png \
    PNGs/cards/Set_B/large/card_b_c4_large.png \
    PNGs/cards/Set_B/large/card_b_c5_large.png \
    PNGs/cards/Set_B/large/card_b_c6_large.png \
    PNGs/cards/Set_B/large/card_b_c7_large.png \
    PNGs/cards/Set_B/large/card_b_c8_large.png \
    PNGs/cards/Set_B/large/card_b_c9_large.png \
    PNGs/cards/Set_B/large/card_b_ca_large.png \
    PNGs/cards/Set_B/large/card_b_cj_large.png \
    PNGs/cards/Set_B/large/card_b_ck_large.png \
    PNGs/cards/Set_B/large/card_b_cq_large.png \
    PNGs/cards/Set_B/large/card_b_d10_large.png \
    PNGs/cards/Set_B/large/card_b_d2_large.png \
    PNGs/cards/Set_B/large/card_b_d3_large.png \
    PNGs/cards/Set_B/large/card_b_d4_large.png \
    PNGs/cards/Set_B/large/card_b_d5_large.png \
    PNGs/cards/Set_B/large/card_b_d6_large.png \
    PNGs/cards/Set_B/large/card_b_d7_large.png \
    PNGs/cards/Set_B/large/card_b_d8_large.png \
    PNGs/cards/Set_B/large/card_b_d9_large.png \
    PNGs/cards/Set_B/large/card_b_da_large.png \
    PNGs/cards/Set_B/large/card_b_dj_large.png \
    PNGs/cards/Set_B/large/card_b_dk_large.png \
    PNGs/cards/Set_B/large/card_b_dq_large.png \
    PNGs/cards/Set_B/large/card_b_h10_large.png \
    PNGs/cards/Set_B/large/card_b_h2_large.png \
    PNGs/cards/Set_B/large/card_b_h3_large.png \
    PNGs/cards/Set_B/large/card_b_h4_large.png \
    PNGs/cards/Set_B/large/card_b_h5_large.png \
    PNGs/cards/Set_B/large/card_b_h6_large.png \
    PNGs/cards/Set_B/large/card_b_h7_large.png \
    PNGs/cards/Set_B/large/card_b_h8_large.png \
    PNGs/cards/Set_B/large/card_b_h9_large.png \
    PNGs/cards/Set_B/large/card_b_ha_large.png \
    PNGs/cards/Set_B/large/card_b_hj_large.png \
    PNGs/cards/Set_B/large/card_b_hk_large.png \
    PNGs/cards/Set_B/large/card_b_hq_large.png \
    PNGs/cards/Set_B/large/card_b_s10_large.png \
    PNGs/cards/Set_B/large/card_b_s2_large.png \
    PNGs/cards/Set_B/large/card_b_s3_large.png \
    PNGs/cards/Set_B/large/card_b_s4_large.png \
    PNGs/cards/Set_B/large/card_b_s5_large.png \
    PNGs/cards/Set_B/large/card_b_s6_large.png \
    PNGs/cards/Set_B/large/card_b_s7_large.png \
    PNGs/cards/Set_B/large/card_b_s8_large.png \
    PNGs/cards/Set_B/large/card_b_s9_large.png \
    PNGs/cards/Set_B/large/card_b_sa_large.png \
    PNGs/cards/Set_B/large/card_b_sj_large.png \
    PNGs/cards/Set_B/large/card_b_sk_large.png \
    PNGs/cards/Set_B/large/card_b_sq_large.png \
    PNGs/cards/Set_B/small/card_b_c10.png \
    PNGs/cards/Set_B/small/card_b_c2.png \
    PNGs/cards/Set_B/small/card_b_c3.png \
    PNGs/cards/Set_B/small/card_b_c4.png \
    PNGs/cards/Set_B/small/card_b_c5.png \
    PNGs/cards/Set_B/small/card_b_c6.png \
    PNGs/cards/Set_B/small/card_b_c7.png \
    PNGs/cards/Set_B/small/card_b_c8.png \
    PNGs/cards/Set_B/small/card_b_c9.png \
    PNGs/cards/Set_B/small/card_b_ca.png \
    PNGs/cards/Set_B/small/card_b_cj.png \
    PNGs/cards/Set_B/small/card_b_ck.png \
    PNGs/cards/Set_B/small/card_b_cq.png \
    PNGs/cards/Set_B/small/card_b_d10.png \
    PNGs/cards/Set_B/small/card_b_d2.png \
    PNGs/cards/Set_B/small/card_b_d3.png \
    PNGs/cards/Set_B/small/card_b_d4.png \
    PNGs/cards/Set_B/small/card_b_d5.png \
    PNGs/cards/Set_B/small/card_b_d6.png \
    PNGs/cards/Set_B/small/card_b_d7.png \
    PNGs/cards/Set_B/small/card_b_d8.png \
    PNGs/cards/Set_B/small/card_b_d9.png \
    PNGs/cards/Set_B/small/card_b_da.png \
    PNGs/cards/Set_B/small/card_b_dj.png \
    PNGs/cards/Set_B/small/card_b_dk.png \
    PNGs/cards/Set_B/small/card_b_dq.png \
    PNGs/cards/Set_B/small/card_b_h10.png \
    PNGs/cards/Set_B/small/card_b_h2.png \
    PNGs/cards/Set_B/small/card_b_h3.png \
    PNGs/cards/Set_B/small/card_b_h4.png \
    PNGs/cards/Set_B/small/card_b_h5.png \
    PNGs/cards/Set_B/small/card_b_h6.png \
    PNGs/cards/Set_B/small/card_b_h7.png \
    PNGs/cards/Set_B/small/card_b_h8.png \
    PNGs/cards/Set_B/small/card_b_h9.png \
    PNGs/cards/Set_B/small/card_b_ha.png \
    PNGs/cards/Set_B/small/card_b_hj.png \
    PNGs/cards/Set_B/small/card_b_hk.png \
    PNGs/cards/Set_B/small/card_b_hq.png \
    PNGs/cards/Set_B/small/card_b_s10.png \
    PNGs/cards/Set_B/small/card_b_s2.png \
    PNGs/cards/Set_B/small/card_b_s3.png \
    PNGs/cards/Set_B/small/card_b_s4.png \
    PNGs/cards/Set_B/small/card_b_s5.png \
    PNGs/cards/Set_B/small/card_b_s6.png \
    PNGs/cards/Set_B/small/card_b_s7.png \
    PNGs/cards/Set_B/small/card_b_s8.png \
    PNGs/cards/Set_B/small/card_b_s9.png \
    PNGs/cards/Set_B/small/card_b_sa.png \
    PNGs/cards/Set_B/small/card_b_sj.png \
    PNGs/cards/Set_B/small/card_b_sk.png \
    PNGs/cards/Set_B/small/card_b_sq.png \
    PNGs/chips/large/chip_biege_flat_large.png \
    PNGs/chips/large/chip_biege_top_large.png \
    PNGs/chips/large/chip_bigblind_flat_large.png \
    PNGs/chips/large/chip_bigblind_top_large.png \
    PNGs/chips/large/chip_black_flat_large.png \
    PNGs/chips/large/chip_black_top_large.png \
    PNGs/chips/large/chip_blue_flat_large.png \
    PNGs/chips/large/chip_blue_top_large.png \
    PNGs/chips/large/chip_dealer_flat_large.png \
    PNGs/chips/large/chip_dealer_top_large.png \
    PNGs/chips/large/chip_gray_flat_large.png \
    PNGs/chips/large/chip_gray_top_large.png \
    PNGs/chips/large/chip_green_flat_large.png \
    PNGs/chips/large/chip_green_top_large.png \
    PNGs/chips/large/chip_lightblue_flat_large.png \
    PNGs/chips/large/chip_lightblue_top_large.png \
    PNGs/chips/large/chip_pink_flat_large.png \
    PNGs/chips/large/chip_pink_top_large.png \
    PNGs/chips/large/chip_purple_flat_large.png \
    PNGs/chips/large/chip_purple_top_large.png \
    PNGs/chips/large/chip_red_flat_large.png \
    PNGs/chips/large/chip_red_top_large.png \
    PNGs/chips/large/chip_smallblind_flat_large.png \
    PNGs/chips/large/chip_smallblind_top_large.png \
    PNGs/chips/large/chip_white_flat_large.png \
    PNGs/chips/large/chip_white_top_large.png \
    PNGs/chips/large/chip_yellow_flat_large.png \
    PNGs/chips/large/chip_yellow_top_large.png \
    PNGs/chips/small/chip_biege_flat.png \
    PNGs/chips/small/chip_biege_top.png \
    PNGs/chips/small/chip_bigblind_flat.png \
    PNGs/chips/small/chip_bigblind_top.png \
    PNGs/chips/small/chip_black_flat.png \
    PNGs/chips/small/chip_black_top.png \
    PNGs/chips/small/chip_blue_flat.png \
    PNGs/chips/small/chip_blue_top.png \
    PNGs/chips/small/chip_dealer_flat.png \
    PNGs/chips/small/chip_dealer_top.png \
    PNGs/chips/small/chip_gray_flat.png \
    PNGs/chips/small/chip_gray_top.png \
    PNGs/chips/small/chip_green_flat.png \
    PNGs/chips/small/chip_green_top.png \
    PNGs/chips/small/chip_lightblue_flat.png \
    PNGs/chips/small/chip_lightblue_top.png \
    PNGs/chips/small/chip_pink_flat.png \
    PNGs/chips/small/chip_pink_top.png \
    PNGs/chips/small/chip_purple_flat.png \
    PNGs/chips/small/chip_purple_top.png \
    PNGs/chips/small/chip_red_flat.png \
    PNGs/chips/small/chip_red_top.png \
    PNGs/chips/small/chip_smallblind_flat.png \
    PNGs/chips/small/chip_smallblind_top.png \
    PNGs/chips/small/chip_white_flat.png \
    PNGs/chips/small/chip_white_top.png \
    PNGs/chips/small/chip_yellow_flat.png \
    PNGs/chips/small/chip_yellow_top.png \
    PNGs/decks/large/deck_1_large.png \
    PNGs/decks/large/deck_2_large.png \
    PNGs/decks/large/deck_3_large.png \
    PNGs/decks/large/deck_4_large.png \
    PNGs/decks/large/deck_5_large.png \
    PNGs/decks/large/deck_6_large.png \
    PNGs/decks/small/deck_1.png \
    PNGs/decks/small/deck_2.png \
    PNGs/decks/small/deck_3.png \
    PNGs/decks/small/deck_4.png \
    PNGs/decks/small/deck_5.png \
    PNGs/decks/small/deck_6.png \
    PNGs/extra/card_empty.png \
    PNGs/extra/card_empty_large.png \
    PNGs/extra/card_selected.png \
    PNGs/extra/card_selected_large.png
